name: ixia-c
nodes:
  - name: otg
    type: IXIA_TG
    version: local
    services:
      443:
        name: https
        inside: 443
      40051:
        name: grpc
        inside: 40051
      50051:
        name: gnmi
        inside: 50051
links:
  - a_node: otg
    a_int: eth1
    z_node: otg
    z_int: eth2
