version: "2.4"

services:
  
  keng-license-server:
    image: docker-local-athena.artifactory.it.keysight.com/keng-license-server:latest
    container_name: keng-license-server
    restart: always
    ports:
      - "7443:7443"
      - "9443:9443"
    command:
      - "--accept-eula"
      - "--debug"
