name: K8S B2B eth0 CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Setup K8S cluster
        run: |
          GITHUB_USER=${{ secrets.ENV_GITHUB_USER }} GITHUB_PAT=${{ secrets.ENV_GITHUB_PAT }} ./do.sh new_k8s_cluster
      - name: Deploy OTG back-to-back topology with eth0
        run: |
          GITHUB_USER=${{ secrets.ENV_GITHUB_USER }} GITHUB_PAT=${{ secrets.ENV_GITHUB_PAT }} ./do.sh topo new k8seth0
      - name: Run go tests
        run: |
          ./do.sh pregotest
          ./do.sh gotest -tags="all" -run="^TestUdpHeaderEth0$"
      # - name: Get container logs
      #   if: always()
      #   run: |
      #     ./do.sh topo logs cpdp
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: generated-artifacts
          path: |
            logs
      - name: Teardown OTG back-to-back topology with eth0
        run: |
          ./do.sh topo rm k8seth0
