name: Licensed CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Deploy back-to-back licensed distribution of ixia-c
        run: |
          GITHUB_USER=${{ secrets.ENV_GITHUB_USER }} GITHUB_PAT=${{ secrets.ENV_GITHUB_PAT }} ./do.sh topo new lic
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Run go tests
        run: |
          ./do.sh pregotest
          ./do.sh gotest -tags="feature"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run python tests
        run: |
          ./do.sh prepytest
          ./do.sh pytest -m feature
      - name: Get container logs
        if: always()
        run: |
          ./do.sh topo logs lic
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: generated-artifacts
          path: |
            logs
      - name: Teardown back-to-back licensed distribution of ixia-c
        run: |
          ./do.sh topo rm lic
